In [1]:
import numpy as np

In [2]:
import numpy as np

In [12]:
a=np.arange(24).reshape(6,4)
b=np.arange(24).reshape(4,6)
print(a)
rg=np.random.default_rng(1)
d=rg.random((2, 3))
print(d)
def f(x, y):
    return 10 * x + y
b = np.fromfunction(f, (5, 4), dtype=int)
b
b[2, 3]
b[0:5, 1]  # each row in the second column of b
b[:, 1]    # equivalent to the previous example
b[1:3, :]  # each column in the second and third row of b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


array([[10, 11, 12, 13],
       [20, 21, 22, 23]])